# Generated by Django 4.2.4 on 2023-09-16 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('carnet', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'alumnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'carreras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion_periodo', models.IntegerField()),
                ('numero_semestre', models.IntegerField()),
            ],
            options={
                'db_table': 'cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'edificio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=5)),
                ('dias_semana', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'horario_cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'horarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'mobiliario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'periodos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salones',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('disponible', models.IntegerField()),
            ],
            options={
                'db_table': 'salones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo_fin', models.ForeignKey(blank=True, db_column='periodo_fin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='docentes_periodo_fin_set', to='asignacion_curso.periodos')),
                ('periodo_inicio', models.ForeignKey(blank=True, db_column='periodo_inicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asignacion_curso.periodos')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnosCursos',
            fields=[
                ('alumno_carnet', models.OneToOneField(db_column='alumno_carnet', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asignacion_curso.alumnos')),
                ('semestre', models.IntegerField()),
                ('ciclo', models.IntegerField()),
            ],
            options={
                'db_table': 'alumnos_cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarreraCursos',
            fields=[
                ('carrera', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asignacion_curso.carreras')),
            ],
            options={
                'db_table': 'carrera_cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarreraEdificio',
            fields=[
                ('carrera', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asignacion_curso.carreras')),
            ],
            options={
                'db_table': 'carrera_edificio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursosSalones',
            fields=[
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asignacion_curso.salones')),
            ],
            options={
                'db_table': 'cursos_salones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocentesCursos',
            fields=[
                ('docente', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asignacion_curso.docentes')),
                ('titular', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'docentes_cursos',
                'managed': False,
            },
        ),
    ]
